version: '2'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=master
    - MYSQL_USER=master
    - MYSQL_PASSWORD=masrter
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
    ports:
    - 3310:3306